# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  lint: 
      staticcheck ./...
      go vet ./...

  tidy:
    - go mod tidy -v
    - go mod vendor -v

  test:
    - go test -v ./...

  run:
    - go run -tags="debug" .

  fmt:
    - go fmt ./...

  web-serve:
    - go run github.com/hajimehoshi/wasmserve@latest -tags="debug" . &
    - sleep 3
    - watchexec --exts go curl localhost:8080/_notify