# https://taskfile.dev

version: '3'

tasks:
  default:
    - task --list-all

  lint: 
    - go run github.com/nishanths/exhaustive/cmd/exhaustive@latest ./...
    - go run honnef.co/go/tools/cmd/staticcheck@latest ./...
    - go vet ./...

  release:
    deps: [tidy, lint, test, fmt]
    cmds:
      - go build -tags="release"

  tidy:
    - go mod tidy -v
    - go mod vendor -v

  test:
    - go test -v ./...

  run:
    - go run .

  fmt:
    - go fmt ./...

  web-serve:
    - go run github.com/hajimehoshi/wasmserve@latest . &
    - sleep 3
    - watchexec --exts go curl localhost:8080/_notify