help: 
    just --list

develop:
    w4 watch target/wasm32-unknown-unknown/debug/cart.wasm

bundle: 
    cargo build --release
    mkdir -p target/bundled
    wasm-opt ./target/wasm32-unknown-unknown/release/cart.wasm -o ./target/bundled/cart_min.wasm -Oz  --converge --strip-debug --strip-dwarf --vacuum --rse --remove-unused-names --remove-unused-module-elements
    w4 bundle ./target/bundled/cart_min.wasm --html ./target/bundled/cart_out.html