Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false